export default [
  {
    title: "Dashboard",
    group: "dashboard",
    icon: "dashboard",
    items: [
      { name: "Operational", title: "Operational", prependIcon: "dashboard" },
      { name: "Analytical", title: "Analytical", prependIcon: "dashboard" },
    ],
  },
  { header: "App" },
  { icon: "contacts", title: "Contacts", name: "Contacts" },
  { icon: "chat", title: "Chat", name: "Chat" },

  { header: "Style & User Interface" },
  { icon: "color_lens", title: "Color", name: "ColorsUI" },
  { icon: "collections", title: "Icons", name: "IconsView" },
  { icon: "help", title: "Helpers", name: "HelpersView" },
  {
    icon: "rounded_corner",
    title: "Border Radius",
    name: "BorderRadius",
    badge: "new",
  },
  {
    icon: "text_fields",
    title: "Text & Typography",
    name: "TextTypographyView",
  },
  { icon: "text_fields", title: "Typography", name: "TypographyView" },
  { icon: "slideshow", title: "Motion", name: "Transitions" },
  { title: "Programmatic Scrolling", name: "Scroll" },
  { icon: "input", title: "Forms", name: "Forms" },

  { header: "Pages" },
  { icon: "people", title: "Profile", name: "ProfileView" },
  { icon: "timer", title: "Coming Soon", name: "ComingSoon" },
  { icon: "build", title: "Maintenance", name: "MaintenancePage" },
  {
    title: "Authentication",
    group: "pages/authentication",
    icon: "lock",
    items: [
      { name: "LoginPage", title: "Login" },
      { name: "SignupPage", title: "Sign Up" },
      { name: "ForgotPasswordPage", title: "Forgot Password" },
      { name: "LockScreenPage", title: "Lock Screen" },
    ],
  },
  {
    title: "Error",
    group: "pages/error",
    icon: "error",
    items: [
      { name: "Error404", title: "404" },
      { name: "Error500", title: "500" },
    ],
  },
  { header: "UI Components" },
  {
    title: "Charts",
    group: "charts",
    icon: "insert_chart",
    items: [
      { name: "SparkLine", title: "Spark Line", icon: "offline_bolt" },
      { name: "ChartJs", title: "ChartJS", icon: "insert_chart_outlined" },
    ],
  },
  {
    title: "Widgets",
    group: "widgets",
    icon: "widgets",
    items: [
      { name: "CardWidgets", title: "Cards" },
      { name: "ListWidgets", title: "Lists" },
      { name: "StatisticWidgets", title: "Statistic" },
      { name: "ChartWidgets", title: "Chart" },
      { name: "DocumentWidgets", title: "Document Cards" },
      // { name: 'SocialWidgets', title: 'Social' },
    ],
  },
  {
    title: "Vuetify",
    group: "components",
    icon: "dashboard",
    items: [
      { name: "ApiExplorerView", title: "Api Explorer" },
      { name: "AlertsView", title: "Alerts" },
      { name: "AvatarsView", title: "Avatars" },
      { name: "BadgeView", title: "Badges" },
      { name: "BannersView", title: "Banners" },
      {
        title: "Bars",
        group: "bars",
        namespace: "components",
        items: [
          { name: "AppBarsView", title: "App Bars" },
          { name: "ToolbarView", title: "Toolbar" },
          { name: "SystemBarsView", title: "System bars" },
        ],
      },
      { name: "BottomNavigationView", title: "Bottom Navigation" },
      { name: "BottomSheetsView", title: "Bottom Sheets" },
      { name: "Breadcrumbs", title: "Breadcrumbs" },
      {
        title: "Buttons",
        group: "buttons",
        namespace: "components",
        items: [
          { name: "Buttons", title: "Buttons", exact: true },
          { name: "FloatingActionButtons", title: "Floating Action" },
          { name: "ButtonGroups", title: "Button Groups" },
        ],
      },
      { name: "Calendars", title: "Calendars" },
      { name: "Cards", title: "Cards" },
      { name: "Carousels", title: "Carousels" },
      {
        title: "Chips",
        group: "chips",
        namespace: "components",
        items: [
          { name: "Chips", title: "Chips", exact: true },
          { name: "ChipGroups", title: "Chip Groups" },
        ],
      },
      { name: "Dialogs", title: "Dialogs" },
      { name: "DividersView", title: "Dividers" },
      { name: "ExpansionPanels", title: "Expansion Panels" },
      { name: "Footer", title: "Footers" },
      {
        title: "Form Control",
        group: "forms-control",
        namespace: "components",
        items: [
          { name: "Autocompletes", title: "Autocompletes", exact: true },
          { name: "Combobox", title: "Combobox" },
          { name: "FileInputs", title: "File Inputs" },
          { name: "Forms", title: "Forms" },
          { name: "Inputs", title: "Inputs" },
          { name: "OverflowBtns", title: "Overflow Buttons" },
          { name: "Selects", title: "Selects" },
          { name: "SelectionControls", title: "Selection Controls" },
          { name: "Sliders", title: "Sliders" },
          { name: "Textarea", title: "Textareas" },
          { name: "Textfields", title: "Textfields" },
        ],
      },
      { name: "Grids", title: "Grids" },
      {
        title: "Groups",
        group: "groups",
        namespace: "components",
        items: [
          { name: "ItemGroups", title: "Item Groups" },
          { name: "SlideGroups", title: "Slide Groups" },
          { name: "Windows", title: "Windows" },
        ],
      },
      { name: "Hover", title: "Hover" },
      { name: "Icons", title: "Icons" },
      { name: "Images", title: "Images" },
      { name: "Lazy", title: "Lazy" },

      {
        title: "Lists",
        group: "lists",
        namespace: "components",
        items: [
          { name: "Lists", title: "List", exact: true },
          { name: "ItemGroupView", title: "Item Group" },
        ],
      },
      { name: "Menus", title: "Menus" },
      { name: "NavigationDrawers", title: "Navigation Drawers" },
      { name: "Overlays", title: "Overlays" },
      { name: "Paginations", title: "Paginations" },
      { name: "Parallax", title: "Parallax" },
      {
        title: "Pickers",
        group: "pickers",
        namespace: "components",
        items: [
          { name: "ColorPickers", title: "Color Pickers" },
          { name: "DatePickers", title: "Date Pickers" },
          { name: "TimePickers", title: "TIme Pickers" },
        ],
      },
      {
        title: "Progress",
        group: "progress",
        namespace: "components",
        items: [
          { name: "CircularProgress", title: "Circular" },
          { name: "LinearProgress", title: "Linear" },
        ],
      },
      { name: "Ratings", title: "Ratings" },
      { name: "Sheets", title: "Sheets" },
      { name: "SkeletonLoaders", title: "Skeleton Loaders" },
      { name: "Snackbars", title: "Snackbars" },
      { name: "Steppers", title: "Steppers" },
      { name: "Subheaders", title: "Subheaders" },
      {
        title: "Tables",
        group: "tables",
        namespace: "components",
        items: [
          { name: "DataIterators", title: "Data Iterators" },
          { name: "SimpleTables", title: "Simple Tables" },
          { name: "DataTables", title: "Data Tables" },
        ],
      },
      { name: "Tabs", title: "Tabs" },
      { name: "Timelines", title: "Timelines" },
      { name: "Tooltips", title: "Tooltips" },
      { name: "Treeview", title: "Treeview" },
    ],
  },
  { header: "Directives" },
  {
    title: "Directives",
    group: "directives",
    icon: "mdi-function",
    items: [
      { name: "Intersect", title: "Intersect" },
      { name: "Mutate", title: "Mutate" },
      { name: "Resizing", title: "Resizing" },
      { name: "Ripples", title: "Ripples" },
      { name: "Scrolling", title: "Scrolling" },
    ],
  },
  // {
  //   icon: 'fas fa-file',
  //   title: 'Document',
  //   href: 'http://doc-vuse-v1.hexesis.com',
  //   target: '_blank'
  // }
];
